import { Bebas_Neue, Montserrat } from "next/font/google";
import "./globals.css";

import IntroSplash from "@/components/layout/Introsplash";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import BackToTop from "@/components/utils/BackToTopButton";

import LocalBusinessJsonLd from "@/components/seo/LocalBusinessJsonLd";
import { SITE_CONFIG } from "@/data/site-confiig";

export const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  // Required for relative OG/Twitter image URLs (including the
  // dynamic one generated by app/opengraph-image.jsx) to resolve to
  // absolute URLs — without this, social platforms can't fetch them.
  metadataBase: new URL(SITE_CONFIG.url),

  // title.template applies "%s | HOME Sports Bar" to every child
  // page's title automatically — each page.js only needs to set its
  // own short title (e.g. "Menu"), not the full brand suffix.
  title: {
    default: SITE_CONFIG.fullName,
    template: `%s | ${SITE_CONFIG.name}`,
  },
  description: SITE_CONFIG.description,
  keywords: SITE_CONFIG.keywords,

  alternates: { canonical: "/" },

  openGraph: {
    type: "website",
    siteName: SITE_CONFIG.name,
    title: SITE_CONFIG.fullName,
    description: SITE_CONFIG.description,
    url: SITE_CONFIG.url,
    locale: "en_US",
    // Deliberately NOT setting `images` here — app/opengraph-image.jsx
    // is auto-detected by Next.js and injected automatically. Setting
    // both would risk duplicate <meta> tags.
  },

  twitter: {
    card: "summary_large_image",
    title: SITE_CONFIG.fullName,
    description: SITE_CONFIG.description,
  },

  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bebas.variable} ${montserrat.variable} h-full antialiased`}
    >
      <head>
        <meta name="apple-mobile-web-app-title" content="Home Sports Bar" />
      </head>
      <body className="min-h-full flex flex-col">
        <LocalBusinessJsonLd />
        <IntroSplash />
        <BackToTop />
        <main className="relative flex flex-1 flex-col">
          <Navbar />
          <span className="pt-16">{children}</span>
          {/* {children} */}
          <Footer />
        </main>
      </body>
    </html>
  );
}
